image:
  file: .gitpod.Dockerfile

tasks:
  # --------------------------------------
  #  SETUP CQLSH and Create DB Workshop
  # --------------------------------------
  - name: setup-cqlsh
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    before: |
      mkdir /workspace/workshop-spring-reactive/tools
      cd /workspace/workshop-spring-reactive/tools
      wget https://downloads.datastax.com/enterprise/cqlsh-astra.tar.gz \
          && tar xvzf cqlsh-astra.tar.gz \
          && rm -f cqlsh-astra.tar.gz
      clear
      cd /workspace/workshop-spring-reactive
      chmod 700 /workspace/workshop-spring-reactive/cqlsh
    command: |
      clear
      cd /workspace/workshop-spring-reactive
      npm exec astra-setup workshops spring_petclinic
      clear
      set -a
      source .env
      set +a

  # ------------------------------------
  # SETUP USER INTERFACE
  # ------------------------------------
  - name: spring-petclinic-angular
    init: |
      gp open README.md
      cd /workspace/workshop-spring-reactive/spring-petclinic-angular
      npm install --silent
      npm run build --silent
    command: |
      cd /workspace/workshop-spring-reactive/spring-petclinic-angular
      echo "export const environment = {production: false, REST_API_URL: '$(gp url 9966)/petclinic/api/'};" > /workspace/workshop-spring-reactive/spring-petclinic-angular/src/environments/environment.ts 
    env:
      NG_CLI_ANALYTICS: ci
  - name: spring-petclinic-reactive
    command: |
     mvn clean
     
ports:
  - port: 4200
    onOpen: open-browser
    visibility: public
  - port: 9966
    onOpen: open-browser
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - GabrielBB.vscode-lombok
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
